Force load function definition if not available
Furthermore, also make sure that aliases don't get expanded after
editing a function

diff --git a/.config/zsh/functions/funced b/.config/zsh/functions/funced
--- a/.config/zsh/functions/funced
+++ b/.config/zsh/functions/funced
@@ -11,9 +11,22 @@ funced () {
 		[ "$name_type" = " function" ] && zed -f "$1"
 		return "$?"
 	else
-		local tmpname="$(mktemp -t zsh_funced.XXXXXXXXXXXX)" 
+		local tmppath="$(mktemp -d "${TMPPREFIX}-${USER}XXXX")"
+
+		if [ "$?" -ne 0 ];then
+			2>&1 echo "Can't create tmp dir for tmp func, exiting"
+			return 1
+		fi
+
+		local tmpname="${tmppath}/$1"
+
 		if [ "$name_type" = " function" ] > /dev/null
 		then
+			if which "$1" | grep -q "^ \+# undefined"
+			then
+				echo "Forcing definition load of $1"
+				autoload -Uz +X "$1"
+			fi
 			which "$1" > "$tmpname"
 		elif [ "$name_type" = " command" ]
 		then
@@ -25,28 +38,17 @@ funced () {
 			echo "I can't edit an alias :|" 2>&1
 			return 1
 		fi
-		while true
-		do
-			$EDITOR "$tmpname"
-			source "$tmpname"
-			local retcode="$?" 
-			if [ "$retcode" -ne 0 ]
-			then
-				local answer="" 
-				echo "$retcode"
-				while test -z "$answer"
-				do
-					printf "Edit the file again? [Y/n] "
-					read -r answer
-				done
-				if ! [[ "$answer" =~ [Nn][Oo]? ]]
-				then
-					continue
-				fi
-			fi
-			break
-		done
-		rm -vi -vi -vi -vi -f "$tmpname" > /dev/null
+
+		$EDITOR "$tmpname"
+
+		fpath=("$tmppath" $fpath)
+		unfunction "$1"
+		autoload -Uz +X "$1"
+
+		rm -f "$tmpname" > /dev/null
+		rmdir "$tmppath" > /dev/null
+		fpath[1]=()
+
 		return "${retcode:-0}"
 	fi
 }
diff --git a/.config/zsh/functions/funcsave b/.config/zsh/functions/funcsave
--- a/.config/zsh/functions/funcsave
+++ b/.config/zsh/functions/funcsave
@@ -1,15 +1,23 @@
-funcsave() {
-	local store_override="${ZFUNC_DIR:-${HOME}/.config/zsh/functions}"
-	if ! [ -d "${store_override}" ];then
+funcsave () {
+	local store_override="${ZFUNC_DIR:-${HOME}/.config/zsh/functions}" 
+	if ! [ -d "${store_override}" ]
+	then
 		mkdir -p "${store_override}"
 	fi
-	if ! [ -d "${store_override}" ];then
-		2>&1 echo "Can't store overrides at ${store_override}"
+	if ! [ -d "${store_override}" ]
+	then
+		echo "Can't store overrides at ${store_override}" 2>&1
 		return 1
 	fi
-
-	for arg in $@;do
-		if functions "${arg}" > /dev/null;then
+	for arg in $@
+	do
+		if functions "${arg}" > /dev/null
+		then
+			if which "${arg}" | grep -q "# undefined"
+			then
+				autoload -Uz +X "${arg}"
+				echo "Forcing definition load of ${arg}"
+			fi
 			which "${arg}" > "${store_override}/${arg}"
 		fi
 	done
